//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortesAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testeftEntities : DbContext
    {
        public testeftEntities()
            : base("name=testeftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<configurations> configurations { get; set; }
        public virtual DbSet<occurrences> occurrences { get; set; }
        public virtual DbSet<processes> processes { get; set; }
        public virtual DbSet<stations> stations { get; set; }
    }
}
