//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class occurrences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public occurrences()
        {
            this.processes = new HashSet<processes>();
        }
    
        public int id { get; set; }
        public int station_id { get; set; }
        public System.DateTime occurred_when { get; set; }
    
        public virtual stations stations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processes> processes { get; set; }
    }
}
